### ISSUE TITLE
Wrong entrypoint path collected if path includes "ts" anywhere in it

### ISSUE THREAD

**Issue by YevheniiMelikov** [polar-rules/nest-task#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running a task i get an error: 

> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/yevhenii.melikov/Projecjs/abe-backend-rebuild/dist/tasks/main.ts' imported from /Users/yevhenii.melikov/Projects/abe-backend-rebuild/node_modules/@polar-rules/nest-task/dist/esm/core/core.loader.js

Apparently it is trying to access `/Users/yevhenii.melikov/Projecjs/abe-backend-rebuild/dist/tasks/main.ts` instead of `/Users/yevhenii.melikov/Projects/abe-backend-rebuild/dist/tasks/main.js`.
It is hard to find, took me a while to spot the problem. So, it replaced `ts` in `/Projects` with `js` 😄 

### Steps to reproduce

1. create empty nest project in a path that includes 'ts' anywhere as a part of a directory name
2. create a polar task
3. run the task and see the issue reproduced

### Expected behavior

It should replace `ts` at the end of the path, not anywhere it encountered it first

### @polar-rules/nest-task version

0.1.2

### Node.js version

20.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

https://github.com/polar-rules/nest-task/blob/1d7afbf9693df885bd60942d80eaa3f6ec8f34c1/lib/core/project-configuration/project-configuration.main.ts#L32

Can be replaced with:
```typescript
return entrypoint.path.replace(sourceRoot, _Constants.Main.compiledFolder).replace(".ts", ".js");
```
It is not a perfect fix, but should be enough

**Comment by d4ins** [comment]
That's bloody stupid of me. 

Sure, you offered a bit of dirty fix, but you have a correct way of thinking.

We should replace only `[-2]` in extension and this will do the trick.

Probably I should review the project once again for same problems.

**Comment by d4ins** [comment]
@YevheniiMelikov It should be fixed at this point.

I know about one more similar problem, and a task has already been created.

You can go ahead and download the lates version [`0.1.3`](https://www.npmjs.com/package/@polar-rules/nest-task/v/0.1.3);
